# Generated by Django 5.2.7 on 2025-10-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicedesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_contacto', models.CharField(choices=[('email', 'Email'), ('telefono', 'Teléfono'), ('otros', 'Otros')], default='email', max_length=10, verbose_name='Origen del contacto')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(to='servicedesk.categoria', verbose_name='Categorías')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
