# Generated by Django 5.2.7 on 2025-10-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categorias_permitidas',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='servicedesk.categoria', verbose_name='Categorías Permitidas'),
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_contacto', models.CharField(choices=[('email', 'Email'), ('telefono', 'Teléfono'), ('otros', 'Otros')], default='email', max_length=10, verbose_name='Origen del contacto')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.categoria', verbose_name='Categoría')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Servicedesk',
        ),
    ]
